apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kubectl
    project: iu-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/managed-by: kubectl
        project: iu-lms
    spec:
      containers:
        - name: gateway
          image: cr.yandex/crpte7n56g4f5meeem22/iu-lms/gateway
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: /health
