apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sessions-db
  labels:
    app.kubernetes.io/name: sessions-db
    app.kubernetes.io/component: sessions
    app.kubernetes.io/managed-by: kubectl
    project: iu-lms
spec:
  serviceName: sessions-db
  selector:
    matchLabels:
      app.kubernetes.io/name: sessions-db
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sessions-db
        app.kubernetes.io/component: sessions
        app.kubernetes.io/managed-by: kubectl
        project: iu-lms
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          volumeMounts:
            - name: sessions-db-disk
              mountPath: /data
          envFrom:
            - configMapRef:
                name: sessions-db-config
  volumeClaimTemplates:
    - metadata:
        name: sessions-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: yc-network-hdd
        resources:
          requests:
            storage: 4Gi