apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
  labels:
    app.kubernetes.io/name: courses
    app.kubernetes.io/component: courses
    app.kubernetes.io/managed-by: kubectl
    project: iu-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: courses
  template:
    metadata:
      labels:
        app.kubernetes.io/name: courses
        app.kubernetes.io/component: courses
        app.kubernetes.io/managed-by: kubectl
        project: iu-lms
    spec:
      containers:
        - name: courses
          image: cr.yandex/crpte7n56g4f5meeem22/iu-lms/courses
          envFrom:
            - configMapRef:
                name: courses-config
          ports:
            - containerPort: 5000
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:5000"]
