apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  labels:
    app.kubernetes.io/name: tasks
    app.kubernetes.io/component: tasks
    app.kubernetes.io/managed-by: kubectl
    project: iu-lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tasks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tasks
        app.kubernetes.io/component: tasks
        app.kubernetes.io/managed-by: kubectl
        project: iu-lms
    spec:
      containers:
        - name: tasks
          image: cr.yandex/crpte7n56g4f5meeem22/iu-lms/tasks
          envFrom:
            - configMapRef:
                name: tasks-config
          ports:
            - containerPort: 5000
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:5000"]
