name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python dev
        run: sudo apt-get install -y python-dev python3-dev
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build repository
        run: bazel build //...
